In [1]:
# Add Matplotlib inline magic command
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# File to Load (Remember to change these)
video_games_to_load = "Data/video_games.csv"

# Read the all games and video games Data
video_games_df = pd.read_csv(video_games_to_load)

In [3]:
video_games_df

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
video_games_df.shape

(16719, 16)

In [5]:
video_games_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  object
 1   Platform         16719 non-null  object
 2   Year_of_Release  16450 non-null  float64
 3   Genre            16717 non-null  object
 4   Publisher        16665 non-null  object
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Other_Sales      16719 non-null  float64
 9   Global_Sales     16719 non-null  float64
 10  Critic_Score     8137 non-null   float64
 11  Critic_Count     8137 non-null   float64
 12  User_Score       10015 non-null  object
 13  User_Count       7590 non-null   float64
 14  Developer        10096 non-null  object
 15  Rating           9950 non-null   object
dtypes: float64(9), object(7)
memory usage: 2.0+ MB

In [6]:
# Rename Name to name column in video_games_df
video_games_df.columns = video_games_df.columns.str.lower()
video_games_df

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_score,user_count,developer,rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# renaming platform types abrv in video_games_df to match all_games_df platform names using the mapping method
mapping = {'N64':'Nintendo 64','PS':'PlayStation','PS3': 'PlayStation 3','DC':'Dreamcast','X360':'Xbox 360','XOne':'Xbox One',
          'Wii':'Wii','PC':'PC','PS2':'PlayStation 2','PS4':'PlayStation 4','GC':'GameCube','XB':'Xbox','WiiU':'Wii U',
          'GBA':'Game Boy Advance','3DS':'3DS','2600':'Atari','DS':'DS','PSV':'PlayStation Vita','PSP':'PSP','GB':'Game Boy',
           'NES':'Nintendo','PSP':'PlayStation Portable'}
video_games_df['platform'] = video_games_df['platform'].map(mapping)
video_games_df

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_score,user_count,developer,rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,Nintendo,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,Game Boy,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PlayStation 3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,Xbox 360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PlayStation Vita,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,Game Boy Advance,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PlayStation Vita,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
print(video_games_df['platform'].unique())

['Wii' 'Nintendo' 'Game Boy' 'DS' 'Xbox 360' 'PlayStation 3'
 'PlayStation 2' nan 'Game Boy Advance' 'PlayStation 4' '3DS'
 'Nintendo 64' 'PlayStation' 'Xbox' 'PC' 'Atari' 'PlayStation Portable'
 'Xbox One' 'Wii U' 'GameCube' 'Dreamcast' 'PlayStation Vita']

In [9]:
print(video_games_df['platform'].value_counts())

PlayStation 2           2161
DS                      2152
PlayStation 3           1331
Wii                     1320
Xbox 360                1262
PlayStation Portable    1209
PlayStation             1197
PC                       974
Xbox                     824
Game Boy Advance         822
GameCube                 556
3DS                      520
PlayStation Vita         432
PlayStation 4            393
Nintendo 64              319
Xbox One                 247
Wii U                    147
Atari                    133
Nintendo                  98
Game Boy                  98
Dreamcast                 52
Name: platform, dtype: int64

In [10]:
video_games_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16717 non-null  object
 1   platform         16247 non-null  object
 2   year_of_release  16450 non-null  float64
 3   genre            16717 non-null  object
 4   publisher        16665 non-null  object
 5   na_sales         16719 non-null  float64
 6   eu_sales         16719 non-null  float64
 7   jp_sales         16719 non-null  float64
 8   other_sales      16719 non-null  float64
 9   global_sales     16719 non-null  float64
 10  critic_score     8137 non-null   float64
 11  critic_count     8137 non-null   float64
 12  user_score       10015 non-null  object
 13  user_count       7590 non-null   float64
 14  developer        10096 non-null  object
 15  rating           9950 non-null   object
dtypes: float64(9), object(7)
memory usage: 2.0+ MB

In [11]:
video_games_df.isnull().sum()

name                  2
platform            472
year_of_release     269
genre                 2
publisher            54
na_sales              0
eu_sales              0
jp_sales              0
other_sales           0
global_sales          0
critic_score       8582
critic_count       8582
user_score         6704
user_count         9129
developer          6623
rating             6769
dtype: int64

In [12]:
na_values = ["name", "platform", "year_of_release", "genre", "publisher"]
video_games_df.dropna(subset=na_values, inplace=True)

In [13]:
video_games_df

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_score,user_count,developer,rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,Nintendo,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,Game Boy,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PlayStation 3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,Xbox 360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PlayStation Vita,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,Game Boy Advance,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PlayStation Vita,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
video_games_df.isnull().sum()

name                  0
platform              0
year_of_release       0
genre                 0
publisher             0
na_sales              0
eu_sales              0
jp_sales              0
other_sales           0
global_sales          0
critic_score       7964
critic_count       7964
user_score         6109
user_count         8485
developer          6042
rating             6179
dtype: int64

In [15]:
# Check for duplicated rows
video_games_df.duplicated().sum(0)

0

In [16]:
# Drop duplicated rows and verify removal
video_games_df.drop_duplicates()
video_games_df.duplicated().sum(0)

0

In [17]:
video_games_df.dtypes

name                object
platform            object
year_of_release    float64
genre               object
publisher           object
na_sales           float64
eu_sales           float64
jp_sales           float64
other_sales        float64
global_sales       float64
critic_score       float64
critic_count       float64
user_score          object
user_count         float64
developer           object
rating              object
dtype: object

In [18]:
# Change the year_of_release column to the int type and verify column types
video_games_df.loc[:, "year_of_release"] = video_games_df.loc[:, "year_of_release"].astype("int")
video_games_df.dtypes

name                object
platform            object
year_of_release      int32
genre               object
publisher           object
na_sales           float64
eu_sales           float64
jp_sales           float64
other_sales        float64
global_sales       float64
critic_score       float64
critic_count       float64
user_score          object
user_count         float64
developer           object
rating              object
dtype: object

In [19]:
video_games_df.describe()

,year_of_release,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_count
count,15946.000000,15946.000000,15946.000000,15946.000000,15946.00000,15946.000000,7982.000000,7982.000000,7461.000000
mean,2006.837138,0.266758,0.148741,0.071212,0.04881,0.535780,68.997119,26.440992,163.008846
std,5.593405,0.819009,0.512412,0.301199,0.19067,1.563712,13.918755,19.009305,563.932422
min,1980.000000,0.000000,0.000000,0.000000,0.00000,0.010000,13.000000,3.000000,4.000000
25%,2004.000000,0.000000,0.000000,0.000000,0.00000,0.060000,60.000000,12.000000,10.000000
50%,2008.000000,0.080000,0.020000,0.000000,0.01000,0.170000,71.000000,22.000000,24.000000
75%,2011.000000,0.240000,0.110000,0.030000,0.04000,0.470000,79.000000,36.000000,81.000000
max,2020.000000,41.360000,28.960000,10.220000,10.57000,82.530000,98.000000,113.000000,10665.000000

In [20]:
video_games_df

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_score,user_count,developer,rating
0,Wii Sports,Wii,2006,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,Nintendo,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,Game Boy,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PlayStation 3,2016,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,Xbox 360,2006,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PlayStation Vita,2016,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,Game Boy Advance,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PlayStation Vita,2016,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
# Rename platform column
video_games_df = video_games_df.rename(columns={'platform_x': 'platform'})
video_games_df

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_score,user_count,developer,rating
0,Wii Sports,Wii,2006,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,Nintendo,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,Game Boy,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PlayStation 3,2016,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,Xbox 360,2006,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PlayStation Vita,2016,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,Game Boy Advance,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PlayStation Vita,2016,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
#Error testing
value = "7.16.67.56.3"
result_column = video_games_df.loc[video_games_df['user_score'] == value, 'name']
result_column

Series([], Name: name, dtype: object)

In [23]:
video_games_df.loc[0, "name"]

'Wii Sports'

In [24]:
video_games_df.dtypes

name                object
platform            object
year_of_release      int32
genre               object
publisher           object
na_sales           float64
eu_sales           float64
jp_sales           float64
other_sales        float64
global_sales       float64
critic_score       float64
critic_count       float64
user_score          object
user_count         float64
developer           object
rating              object
dtype: object

In [25]:
# Sum of column na_sales, eu_sales, jp_sales, and other_sales.
video_games_df["worldwide_sales"] = (video_games_df["na_sales"] + video_games_df["eu_sales"]
                                    + video_games_df["jp_sales"] + video_games_df["other_sales"])

In [26]:
sales_columns = ['na_sales', 'eu_sales', 'jp_sales', 'other_sales']
video_games_df[sales_columns].sum(axis="columns")

0        82.54
1        40.24
2        35.52
3        32.77
4        31.38
         ...
16714     0.01
16715     0.01
16716     0.01
16717     0.01
16718     0.01
Length: 15946, dtype: float64

In [27]:
video_games_df["worldwide_sales"]

0        82.54
1        40.24
2        35.52
3        32.77
4        31.38
         ...
16714     0.01
16715     0.01
16716     0.01
16717     0.01
16718     0.01
Name: worldwide_sales, Length: 15946, dtype: float64

In [28]:
video_games_df

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_score,user_count,developer,rating,worldwide_sales
0,Wii Sports,Wii,2006,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E,82.54
1,Super Mario Bros.,Nintendo,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN,40.24
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,35.52
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E,32.77
4,Pokemon Red/Pokemon Blue,Game Boy,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN,31.38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PlayStation 3,2016,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN,0.01
16715,LMA Manager 2007,Xbox 360,2006,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN,0.01
16716,Haitaka no Psychedelica,PlayStation Vita,2016,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN,0.01
16717,Spirits & Spells,Game Boy Advance,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN,0.01
16718,Winning Post 8 2016,PlayStation Vita,2016,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN,0.01

In [29]:
#Create an all_video_games_df to hold all sales values before critic score na is dropped. 

all_video_games_df = video_games_df.copy()
all_video_games_df.dtypes

name                object
platform            object
year_of_release      int32
genre               object
publisher           object
na_sales           float64
eu_sales           float64
jp_sales           float64
other_sales        float64
global_sales       float64
critic_score       float64
critic_count       float64
user_score          object
user_count         float64
developer           object
rating              object
worldwide_sales    float64
dtype: object

In [30]:
#drop all na values including those without review scores. This will decreast dataset significantly
video_games_df.dropna(inplace=True)

In [31]:
# Change userscore from object to float
video_games_df['user_score'] = video_games_df['user_score'].astype(float)
video_games_df.dtypes

name                object
platform            object
year_of_release      int32
genre               object
publisher           object
na_sales           float64
eu_sales           float64
jp_sales           float64
other_sales        float64
global_sales       float64
critic_score       float64
critic_count       float64
user_score         float64
user_count         float64
developer           object
rating              object
worldwide_sales    float64
dtype: object

In [32]:
video_games_df

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_score,user_count,developer,rating,worldwide_sales
0,Wii Sports,Wii,2006,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E,82.54
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,35.52
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E,32.77
6,New Super Mario Bros.,DS,2006,Platform,Nintendo,11.28,9.14,6.50,2.88,29.80,89.0,65.0,8.5,431.0,Nintendo,E,29.80
7,Wii Play,Wii,2006,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92,58.0,41.0,6.6,129.0,Nintendo,E,28.91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16667,E.T. The Extra-Terrestrial,Game Boy Advance,2001,Action,NewKidCo,0.01,0.00,0.00,0.00,0.01,46.0,4.0,2.4,21.0,Fluid Studios,E,0.01
16677,Mortal Kombat: Deadly Alliance,Game Boy Advance,2002,Fighting,Midway Games,0.01,0.00,0.00,0.00,0.01,81.0,12.0,8.8,9.0,Criterion Games,M,0.01
16696,Metal Gear Solid V: Ground Zeroes,PC,2014,Action,Konami Digital Entertainment,0.00,0.01,0.00,0.00,0.01,80.0,20.0,7.6,412.0,Kojima Productions,M,0.01
16700,Breach,PC,2011,Shooter,Destineer,0.01,0.00,0.00,0.00,0.01,61.0,12.0,5.8,43.0,Atomic Games,T,0.01
16706,STORM: Frontline Nation,PC,2011,Strategy,Unknown,0.00,0.01,0.00,0.00,0.01,60.0,12.0,7.2,13.0,SimBin,E10+,0.01

In [33]:
all_video_games_df.isnull().sum()

name                  0
platform              0
year_of_release       0
genre                 0
publisher             0
na_sales              0
eu_sales              0
jp_sales              0
other_sales           0
global_sales          0
critic_score       7964
critic_count       7964
user_score         6109
user_count         8485
developer          6042
rating             6179
worldwide_sales       0
dtype: int64

In [34]:
review_columns = ["global_sales", "critic_score", "critic_count", "user_score", "user_count", "developer", "rating"]
all_video_games_df = all_video_games_df.drop(columns=review_columns)
all_video_games_df

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,worldwide_sales
0,Wii Sports,Wii,2006,Sports,Nintendo,41.36,28.96,3.77,8.45,82.54
1,Super Mario Bros.,Nintendo,1985,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77
4,Pokemon Red/Pokemon Blue,Game Boy,1996,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.38
...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PlayStation 3,2016,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01
16715,LMA Manager 2007,Xbox 360,2006,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01
16716,Haitaka no Psychedelica,PlayStation Vita,2016,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01
16717,Spirits & Spells,Game Boy Advance,2003,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01
16718,Winning Post 8 2016,PlayStation Vita,2016,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01

In [36]:
all_video_games_df.to_csv('all_video_games.csv')

In [43]:
platform_agg_df = video_games_df.copy()
platform_agg_df.dropna()
platform_agg_df

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_score,user_count,developer,rating,worldwide_sales
0,Wii Sports,Wii,2006,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E,82.54
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,35.52
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E,32.77
6,New Super Mario Bros.,DS,2006,Platform,Nintendo,11.28,9.14,6.50,2.88,29.80,89.0,65.0,8.5,431.0,Nintendo,E,29.80
7,Wii Play,Wii,2006,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92,58.0,41.0,6.6,129.0,Nintendo,E,28.91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16667,E.T. The Extra-Terrestrial,Game Boy Advance,2001,Action,NewKidCo,0.01,0.00,0.00,0.00,0.01,46.0,4.0,2.4,21.0,Fluid Studios,E,0.01
16677,Mortal Kombat: Deadly Alliance,Game Boy Advance,2002,Fighting,Midway Games,0.01,0.00,0.00,0.00,0.01,81.0,12.0,8.8,9.0,Criterion Games,M,0.01
16696,Metal Gear Solid V: Ground Zeroes,PC,2014,Action,Konami Digital Entertainment,0.00,0.01,0.00,0.00,0.01,80.0,20.0,7.6,412.0,Kojima Productions,M,0.01
16700,Breach,PC,2011,Shooter,Destineer,0.01,0.00,0.00,0.00,0.01,61.0,12.0,5.8,43.0,Atomic Games,T,0.01
16706,STORM: Frontline Nation,PC,2011,Strategy,Unknown,0.00,0.01,0.00,0.00,0.01,60.0,12.0,7.2,13.0,SimBin,E10+,0.01

In [44]:
platform_agg_df = platform_agg_df.dropna()

In [45]:
platform_agg_df["user_score"] = platform_agg_df["user_score"].astype(float)

In [47]:
platform_agg_df

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_score,user_count,developer,rating,worldwide_sales
0,Wii Sports,Wii,2006,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8.0,322.0,Nintendo,E,82.54
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E,35.52
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8.0,192.0,Nintendo,E,32.77
6,New Super Mario Bros.,DS,2006,Platform,Nintendo,11.28,9.14,6.50,2.88,29.80,89.0,65.0,8.5,431.0,Nintendo,E,29.80
7,Wii Play,Wii,2006,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92,58.0,41.0,6.6,129.0,Nintendo,E,28.91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16667,E.T. The Extra-Terrestrial,Game Boy Advance,2001,Action,NewKidCo,0.01,0.00,0.00,0.00,0.01,46.0,4.0,2.4,21.0,Fluid Studios,E,0.01
16677,Mortal Kombat: Deadly Alliance,Game Boy Advance,2002,Fighting,Midway Games,0.01,0.00,0.00,0.00,0.01,81.0,12.0,8.8,9.0,Criterion Games,M,0.01
16696,Metal Gear Solid V: Ground Zeroes,PC,2014,Action,Konami Digital Entertainment,0.00,0.01,0.00,0.00,0.01,80.0,20.0,7.6,412.0,Kojima Productions,M,0.01
16700,Breach,PC,2011,Shooter,Destineer,0.01,0.00,0.00,0.00,0.01,61.0,12.0,5.8,43.0,Atomic Games,T,0.01
16706,STORM: Frontline Nation,PC,2011,Strategy,Unknown,0.00,0.01,0.00,0.00,0.01,60.0,12.0,7.2,13.0,SimBin,E10+,0.01

In [48]:
aggregate_functions_by_name = {
    "year_of_release": "min",
    "developer": "first",
    "na_sales": "sum",
    "eu_sales": "sum",
    "jp_sales": "sum",
    "worldwide_sales": "sum",
    "critic_score": "mean",
    "user_score": "mean",
    "critic_count": "sum",
    "user_count": "sum",
}

platform_agg_df = platform_agg_df.groupby("name").agg(aggregate_functions_by_name)
platform_agg_df

,year_of_release,developer,na_sales,eu_sales,jp_sales,worldwide_sales,critic_score,user_score,critic_count,user_count
name,,,,,,,,,,
Tales of Xillia 2,2012,Bandai Namco Games,0.20,0.12,0.45,0.84,71.0,7.900,59.0,216.0
.hack//Infection Part 1,2002,CyberConnect2,0.49,0.38,0.26,1.26,75.0,8.500,35.0,60.0
.hack//Mutation Part 2,2002,CyberConnect2,0.23,0.18,0.20,0.67,76.0,8.900,24.0,81.0
.hack//Outbreak Part 3,2002,CyberConnect2,0.14,0.11,0.17,0.46,70.0,8.700,23.0,19.0
007 Racing,2000,Eutechnyx,0.30,0.20,0.00,0.53,51.0,4.600,16.0,14.0
...,...,...,...,...,...,...,...,...,...,...
inFAMOUS 2,2011,Sucker Punch,1.05,0.47,0.08,1.82,83.0,8.400,90.0,932.0
inFAMOUS: Second Son,2014,Sucker Punch,1.28,0.98,0.07,2.79,80.0,7.900,90.0,2944.0
nail'd,2010,Techland,0.16,0.04,0.00,0.23,65.0,6.650,85.0,29.0
pro evolution soccer 2011,2010,Konami,0.50,2.01,0.86,4.03,77.0,5.975,102.0,130.0
uDraw Studio: Instant Artist,2011,THQ,0.01,0.01,0.00,0.02,54.0,5.700,5.0,6.0

In [49]:
video_games_df.dtypes

name                object
platform            object
year_of_release      int32
genre               object
publisher           object
na_sales           float64
eu_sales           float64
jp_sales           float64
other_sales        float64
global_sales       float64
critic_score       float64
critic_count       float64
user_score         float64
user_count         float64
developer           object
rating              object
worldwide_sales    float64
dtype: object

In [50]:
platform_agg_df.columns

Index(['year_of_release', 'developer', 'na_sales', 'eu_sales', 'jp_sales',
       'worldwide_sales', 'critic_score', 'user_score', 'critic_count',
       'user_count'],
      dtype='object')

In [51]:
platform_agg_df.loc["Wii Sports"]

year_of_release        2006
developer          Nintendo
na_sales              41.36
eu_sales              28.96
jp_sales               3.77
worldwide_sales       82.54
critic_score           76.0
user_score              8.0
critic_count           51.0
user_count            322.0
Name: Wii Sports, dtype: object

In [52]:
platform_agg_df.to_csv('platform_agg.csv')

In [53]:
#Creating new df for each table to simplify importation. 
details_df = video_games_df[['name', 'platform', 'year_of_release', 'genre', 'publisher', 'developer', 'rating']].copy()
details_df

,name,platform,year_of_release,genre,publisher,developer,rating
0,Wii Sports,Wii,2006,Sports,Nintendo,Nintendo,E
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,Nintendo,E
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,Nintendo,E
6,New Super Mario Bros.,DS,2006,Platform,Nintendo,Nintendo,E
7,Wii Play,Wii,2006,Misc,Nintendo,Nintendo,E
...,...,...,...,...,...,...,...
16667,E.T. The Extra-Terrestrial,Game Boy Advance,2001,Action,NewKidCo,Fluid Studios,E
16677,Mortal Kombat: Deadly Alliance,Game Boy Advance,2002,Fighting,Midway Games,Criterion Games,M
16696,Metal Gear Solid V: Ground Zeroes,PC,2014,Action,Konami Digital Entertainment,Kojima Productions,M
16700,Breach,PC,2011,Shooter,Destineer,Atomic Games,T
16706,STORM: Frontline Nation,PC,2011,Strategy,Unknown,SimBin,E10+

In [54]:
reviews_df = video_games_df[['name', 'critic_score', 'critic_count', 'user_score', 'user_count']].copy()
reviews_df

,name,critic_score,critic_count,user_score,user_count
0,Wii Sports,76.0,51.0,8.0,322.0
2,Mario Kart Wii,82.0,73.0,8.3,709.0
3,Wii Sports Resort,80.0,73.0,8.0,192.0
6,New Super Mario Bros.,89.0,65.0,8.5,431.0
7,Wii Play,58.0,41.0,6.6,129.0
...,...,...,...,...,...
16667,E.T. The Extra-Terrestrial,46.0,4.0,2.4,21.0
16677,Mortal Kombat: Deadly Alliance,81.0,12.0,8.8,9.0
16696,Metal Gear Solid V: Ground Zeroes,80.0,20.0,7.6,412.0
16700,Breach,61.0,12.0,5.8,43.0
16706,STORM: Frontline Nation,60.0,12.0,7.2,13.0

In [55]:
sales_df = video_games_df[['name', 'na_sales', 'eu_sales', 'jp_sales', 'other_sales', 'global_sales']].copy()
sales_df

,name,na_sales,eu_sales,jp_sales,other_sales,global_sales
0,Wii Sports,41.36,28.96,3.77,8.45,82.53
2,Mario Kart Wii,15.68,12.76,3.79,3.29,35.52
3,Wii Sports Resort,15.61,10.93,3.28,2.95,32.77
6,New Super Mario Bros.,11.28,9.14,6.50,2.88,29.80
7,Wii Play,13.96,9.18,2.93,2.84,28.92
...,...,...,...,...,...,...
16667,E.T. The Extra-Terrestrial,0.01,0.00,0.00,0.00,0.01
16677,Mortal Kombat: Deadly Alliance,0.01,0.00,0.00,0.00,0.01
16696,Metal Gear Solid V: Ground Zeroes,0.00,0.01,0.00,0.00,0.01
16700,Breach,0.01,0.00,0.00,0.00,0.01
16706,STORM: Frontline Nation,0.00,0.01,0.00,0.00,0.01

In [56]:
# check for duplicates
duplicates = details_df.duplicated()

# print the rows that are duplicates
print(details_df[duplicates])

#How to handle duplicates?
details_df.to_csv('details.csv')

                name       platform  year_of_release   genre        publisher  \
16233  Madden NFL 13  PlayStation 3             2012  Sports  Electronic Arts

        developer rating
16233  EA Tiburon      E

In [57]:
# check for duplicates
duplicates = reviews_df.duplicated()

# print the rows that are duplicates
print(reviews_df[duplicates])

#How to handle duplicates?
reviews_df.to_csv('reviews.csv')

                              name  critic_score  critic_count  user_score  \
1591   Need for Speed: Most Wanted          83.0          54.0         8.5
11716  Need for Speed: Most Wanted          82.0          19.0         8.5
16233                Madden NFL 13          83.0          22.0         5.5

       user_count
1591        134.0
11716       525.0
16233       101.0

In [58]:
# check for duplicates
duplicates = sales_df.duplicated()

# print the rows that are duplicates
print(sales_df[duplicates])

#How to handle duplicates?
sales_df.to_csv('sales.csv')

                                                name  na_sales  eu_sales  \
6454                             The Incredible Hulk      0.22      0.02
7475                             You Don't Know Jack      0.19      0.00
10280                                   Pimp My Ride      0.10      0.00
10592  Scribblenauts Unmasked: A DC Comics Adventure      0.09      0.00
15487             XGRA: Extreme G Racing Association      0.02      0.00
15662                             The Crew: Wild Run      0.00      0.02

       jp_sales  other_sales  global_sales
6454        0.0         0.02          0.26
7475        0.0         0.01          0.21
10280       0.0         0.01          0.11
10592       0.0         0.01          0.10
15487       0.0         0.00          0.02
15662       0.0         0.00          0.02