In [1]:
# Add Matplotlib inline magic command
%matplotlib inline
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# File to Load (Remember to change these)
video_games_to_load = "Data/video_games.csv"

# Read the all games and video games Data
video_games_df = pd.read_csv(video_games_to_load)

In [3]:
video_games_df.head(10)

,Name,Platform,Year_of_Release,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Critic_Score,Critic_Count,User_Score,User_Count,Developer,Rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
5,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26,NaN,NaN,NaN,NaN,NaN,NaN
6,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.28,9.14,6.50,2.88,29.80,89.0,65.0,8.5,431.0,Nintendo,E
7,Wii Play,Wii,2006.0,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92,58.0,41.0,6.6,129.0,Nintendo,E
8,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.44,6.94,4.70,2.24,28.32,87.0,80.0,8.4,594.0,Nintendo,E
9,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
video_games_df.shape

(16719, 16)

In [5]:
video_games_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16717 non-null  object
 1   Platform         16719 non-null  object
 2   Year_of_Release  16450 non-null  float64
 3   Genre            16717 non-null  object
 4   Publisher        16665 non-null  object
 5   NA_Sales         16719 non-null  float64
 6   EU_Sales         16719 non-null  float64
 7   JP_Sales         16719 non-null  float64
 8   Other_Sales      16719 non-null  float64
 9   Global_Sales     16719 non-null  float64
 10  Critic_Score     8137 non-null   float64
 11  Critic_Count     8137 non-null   float64
 12  User_Score       10015 non-null  object
 13  User_Count       7590 non-null   float64
 14  Developer        10096 non-null  object
 15  Rating           9950 non-null   object
dtypes: float64(9), object(7)
memory usage: 2.0+ MB

In [6]:
# Rename Name to name column in video_games_df
video_games_df.columns = video_games_df.columns.str.lower()
video_games_df

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_score,user_count,developer,rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,X360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PSV,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PSV,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# renaming platform types abrv in video_games_df to match all_games_df platform names using the mapping method
mapping = {'N64':'Nintendo 64','PS':'PlayStation','PS3': 'PlayStation 3','DC':'Dreamcast','X360':'Xbox 360','XOne':'Xbox One',
          'Wii':'Wii','PC':'PC','PS2':'PlayStation 2','PS4':'PlayStation 4','GC':'GameCube','XB':'Xbox','WiiU':'Wii U',
          'GBA':'Game Boy Advance','3DS':'3DS','2600':'Atari','DS':'DS','PSV':'PlayStation Vita','PSP':'PSP','GB':'Game Boy',
           'NES':'Nintendo','PSP':'PlayStation Portable'}
video_games_df['platform'] = video_games_df['platform'].map(mapping)
video_games_df

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_score,user_count,developer,rating
0,Wii Sports,Wii,2006.0,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
1,Super Mario Bros.,Nintendo,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,NaN,NaN,NaN,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
4,Pokemon Red/Pokemon Blue,Game Boy,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16714,Samurai Warriors: Sanada Maru,PlayStation 3,2016.0,Action,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16715,LMA Manager 2007,Xbox 360,2006.0,Sports,Codemasters,0.00,0.01,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16716,Haitaka no Psychedelica,PlayStation Vita,2016.0,Adventure,Idea Factory,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16717,Spirits & Spells,Game Boy Advance,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN
16718,Winning Post 8 2016,PlayStation Vita,2016.0,Simulation,Tecmo Koei,0.00,0.00,0.01,0.00,0.01,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
print(video_games_df['platform'].unique())

['Wii' 'Nintendo' 'Game Boy' 'DS' 'Xbox 360' 'PlayStation 3'
 'PlayStation 2' nan 'Game Boy Advance' 'PlayStation 4' '3DS'
 'Nintendo 64' 'PlayStation' 'Xbox' 'PC' 'Atari' 'PlayStation Portable'
 'Xbox One' 'Wii U' 'GameCube' 'Dreamcast' 'PlayStation Vita']

In [9]:
print(video_games_df['platform'].value_counts())

PlayStation 2           2161
DS                      2152
PlayStation 3           1331
Wii                     1320
Xbox 360                1262
PlayStation Portable    1209
PlayStation             1197
PC                       974
Xbox                     824
Game Boy Advance         822
GameCube                 556
3DS                      520
PlayStation Vita         432
PlayStation 4            393
Nintendo 64              319
Xbox One                 247
Wii U                    147
Atari                    133
Nintendo                  98
Game Boy                  98
Dreamcast                 52
Name: platform, dtype: int64

In [10]:
video_games_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16719 entries, 0 to 16718
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16717 non-null  object
 1   platform         16247 non-null  object
 2   year_of_release  16450 non-null  float64
 3   genre            16717 non-null  object
 4   publisher        16665 non-null  object
 5   na_sales         16719 non-null  float64
 6   eu_sales         16719 non-null  float64
 7   jp_sales         16719 non-null  float64
 8   other_sales      16719 non-null  float64
 9   global_sales     16719 non-null  float64
 10  critic_score     8137 non-null   float64
 11  critic_count     8137 non-null   float64
 12  user_score       10015 non-null  object
 13  user_count       7590 non-null   float64
 14  developer        10096 non-null  object
 15  rating           9950 non-null   object
dtypes: float64(9), object(7)
memory usage: 2.0+ MB

In [11]:
video_games_df.dropna(inplace=True)

In [12]:
video_games_df.isnull().sum()

name               0
platform           0
year_of_release    0
genre              0
publisher          0
na_sales           0
eu_sales           0
jp_sales           0
other_sales        0
global_sales       0
critic_score       0
critic_count       0
user_score         0
user_count         0
developer          0
rating             0
dtype: int64

In [13]:
# Check for duplicated rows
video_games_df.duplicated().sum(0)

0

In [14]:
# Drop duplicated rows and verify removal
video_games_df.drop_duplicates()
video_games_df.duplicated().sum(0)

0

In [15]:
video_games_df.dtypes

name                object
platform            object
year_of_release    float64
genre               object
publisher           object
na_sales           float64
eu_sales           float64
jp_sales           float64
other_sales        float64
global_sales       float64
critic_score       float64
critic_count       float64
user_score          object
user_count         float64
developer           object
rating              object
dtype: object

In [16]:
# Change the year_of_release column to the int type and verify column types
video_games_df.loc[:, "year_of_release"] = video_games_df.loc[:, "year_of_release"].astype("int")
video_games_df.dtypes

name                object
platform            object
year_of_release      int32
genre               object
publisher           object
na_sales           float64
eu_sales           float64
jp_sales           float64
other_sales        float64
global_sales       float64
critic_score       float64
critic_count       float64
user_score          object
user_count         float64
developer           object
rating              object
dtype: object

In [68]:
# Change the year_of_release column to the int type and verify column types
video_games_df['user_score'] = video_games_df['user_score'].astype(float)
video_games_df.dtypes

name                object
platform            object
year_of_release      int32
genre               object
publisher           object
na_sales           float64
eu_sales           float64
jp_sales           float64
other_sales        float64
global_sales       float64
critic_score       float64
critic_count       float64
user_score         float64
user_count         float64
developer           object
rating              object
worldwide_sales    float64
dtype: object

In [17]:
video_games_df.describe()

,year_of_release,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_count
count,6825.000000,6825.000000,6825.000000,6825.000000,6825.000000,6825.000000,6825.000000,6825.000000,6825.000000
mean,2007.436777,0.394484,0.236089,0.064158,0.082677,0.777590,70.272088,28.931136,174.722344
std,4.211248,0.967385,0.687330,0.287570,0.269871,1.963443,13.868572,19.224165,587.428538
min,1985.000000,0.000000,0.000000,0.000000,0.000000,0.010000,13.000000,3.000000,4.000000
25%,2004.000000,0.060000,0.020000,0.000000,0.010000,0.110000,62.000000,14.000000,11.000000
50%,2007.000000,0.150000,0.060000,0.000000,0.020000,0.290000,72.000000,25.000000,27.000000
75%,2011.000000,0.390000,0.210000,0.010000,0.070000,0.750000,80.000000,39.000000,89.000000
max,2016.000000,41.360000,28.960000,6.500000,10.570000,82.530000,98.000000,113.000000,10665.000000

In [18]:
video_games_df

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_score,user_count,developer,rating
0,Wii Sports,Wii,2006,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
6,New Super Mario Bros.,DS,2006,Platform,Nintendo,11.28,9.14,6.50,2.88,29.80,89.0,65.0,8.5,431.0,Nintendo,E
7,Wii Play,Wii,2006,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92,58.0,41.0,6.6,129.0,Nintendo,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16667,E.T. The Extra-Terrestrial,Game Boy Advance,2001,Action,NewKidCo,0.01,0.00,0.00,0.00,0.01,46.0,4.0,2.4,21.0,Fluid Studios,E
16677,Mortal Kombat: Deadly Alliance,Game Boy Advance,2002,Fighting,Midway Games,0.01,0.00,0.00,0.00,0.01,81.0,12.0,8.8,9.0,Criterion Games,M
16696,Metal Gear Solid V: Ground Zeroes,PC,2014,Action,Konami Digital Entertainment,0.00,0.01,0.00,0.00,0.01,80.0,20.0,7.6,412.0,Kojima Productions,M
16700,Breach,PC,2011,Shooter,Destineer,0.01,0.00,0.00,0.00,0.01,61.0,12.0,5.8,43.0,Atomic Games,T
16706,STORM: Frontline Nation,PC,2011,Strategy,Unknown,0.00,0.01,0.00,0.00,0.01,60.0,12.0,7.2,13.0,SimBin,E10+

In [22]:
video_games_df = video_games_df.rename(columns={'platform_x': 'platform'})
video_games_df

,name,platform,year_of_release,genre,publisher,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_score,user_count,developer,rating
0,Wii Sports,Wii,2006,Sports,Nintendo,41.36,28.96,3.77,8.45,82.53,76.0,51.0,8,322.0,Nintendo,E
2,Mario Kart Wii,Wii,2008,Racing,Nintendo,15.68,12.76,3.79,3.29,35.52,82.0,73.0,8.3,709.0,Nintendo,E
3,Wii Sports Resort,Wii,2009,Sports,Nintendo,15.61,10.93,3.28,2.95,32.77,80.0,73.0,8,192.0,Nintendo,E
6,New Super Mario Bros.,DS,2006,Platform,Nintendo,11.28,9.14,6.50,2.88,29.80,89.0,65.0,8.5,431.0,Nintendo,E
7,Wii Play,Wii,2006,Misc,Nintendo,13.96,9.18,2.93,2.84,28.92,58.0,41.0,6.6,129.0,Nintendo,E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16667,E.T. The Extra-Terrestrial,Game Boy Advance,2001,Action,NewKidCo,0.01,0.00,0.00,0.00,0.01,46.0,4.0,2.4,21.0,Fluid Studios,E
16677,Mortal Kombat: Deadly Alliance,Game Boy Advance,2002,Fighting,Midway Games,0.01,0.00,0.00,0.00,0.01,81.0,12.0,8.8,9.0,Criterion Games,M
16696,Metal Gear Solid V: Ground Zeroes,PC,2014,Action,Konami Digital Entertainment,0.00,0.01,0.00,0.00,0.01,80.0,20.0,7.6,412.0,Kojima Productions,M
16700,Breach,PC,2011,Shooter,Destineer,0.01,0.00,0.00,0.00,0.01,61.0,12.0,5.8,43.0,Atomic Games,T
16706,STORM: Frontline Nation,PC,2011,Strategy,Unknown,0.00,0.01,0.00,0.00,0.01,60.0,12.0,7.2,13.0,SimBin,E10+

In [64]:
value = "7.16.67.56.3"
result_column = video_games_df.loc[video_games_df['user_score'] == value, 'name']
result_column

Series([], Name: name, dtype: object)

In [55]:
video_games_df.loc[0, "name"]

'Wii Sports'

In [24]:
video_games_df.dtypes

name                object
platform            object
year_of_release      int32
genre               object
publisher           object
na_sales           float64
eu_sales           float64
jp_sales           float64
other_sales        float64
global_sales       float64
critic_score       float64
critic_count       float64
user_score          object
user_count         float64
developer           object
rating              object
dtype: object

In [29]:
# Sum of column na_sales, eu_sales, jp_sales, and other_sales.
video_games_df["worldwide_sales"] = (video_games_df["na_sales"] + video_games_df["eu_sales"]
                                    + video_games_df["jp_sales"] + video_games_df["other_sales"])

In [33]:
sales_columns = ['na_sales', 'eu_sales', 'jp_sales', 'other_sales']
video_games_df[sales_columns].sum(axis="columns")

0        82.54
2        35.52
3        32.77
6        29.80
7        28.91
         ...
16667     0.01
16677     0.01
16696     0.01
16700     0.01
16706     0.01
Length: 6825, dtype: float64

In [34]:
video_games_df["worldwide_sales"]

0        82.54
2        35.52
3        32.77
6        29.80
7        28.91
         ...
16667     0.01
16677     0.01
16696     0.01
16700     0.01
16706     0.01
Name: worldwide_sales, Length: 6825, dtype: float64

In [37]:
video_games_df.groupby("name").sum().sort_index()

,year_of_release,na_sales,eu_sales,jp_sales,other_sales,global_sales,critic_score,critic_count,user_count,worldwide_sales
name,,,,,,,,,,
Tales of Xillia 2,2012,0.20,0.12,0.45,0.07,0.84,71.0,59.0,216.0,0.84
.hack//Infection Part 1,2002,0.49,0.38,0.26,0.13,1.27,75.0,35.0,60.0,1.26
.hack//Mutation Part 2,2002,0.23,0.18,0.20,0.06,0.68,76.0,24.0,81.0,0.67
.hack//Outbreak Part 3,2002,0.14,0.11,0.17,0.04,0.46,70.0,23.0,19.0,0.46
007 Racing,2000,0.30,0.20,0.00,0.03,0.53,51.0,16.0,14.0,0.53
...,...,...,...,...,...,...,...,...,...,...
inFAMOUS 2,2011,1.05,0.47,0.08,0.22,1.82,83.0,90.0,932.0,1.82
inFAMOUS: Second Son,2014,1.28,0.98,0.07,0.46,2.79,80.0,90.0,2944.0,2.79
nail'd,4020,0.16,0.04,0.00,0.03,0.22,130.0,85.0,29.0,0.23
pro evolution soccer 2011,8040,0.50,2.01,0.86,0.66,4.03,308.0,102.0,130.0,4.03
uDraw Studio: Instant Artist,2011,0.01,0.01,0.00,0.00,0.02,54.0,5.0,6.0,0.02

In [69]:
aggregate_functions_by_name = {
    "year_of_release": ["min"],
    "developer": ["min"],
    "worldwide_sales": ["sum"],
    "critic_score": ["mean"],
    "user_score": ["mean"],
    "critic_count": ["sum"],
    "user_count": ["sum"],
    
}

platform_agg_df = video_games_df.groupby("name").agg(aggregate_functions_by_name).droplevel(1, axis="columns")
platform_agg_df

,year_of_release,developer,worldwide_sales,critic_score,user_score,critic_count,user_count
name,,,,,,,
Tales of Xillia 2,2012,Bandai Namco Games,0.84,71.0,7.900,59.0,216.0
.hack//Infection Part 1,2002,CyberConnect2,1.26,75.0,8.500,35.0,60.0
.hack//Mutation Part 2,2002,CyberConnect2,0.67,76.0,8.900,24.0,81.0
.hack//Outbreak Part 3,2002,CyberConnect2,0.46,70.0,8.700,23.0,19.0
007 Racing,2000,Eutechnyx,0.53,51.0,4.600,16.0,14.0
...,...,...,...,...,...,...,...
inFAMOUS 2,2011,Sucker Punch,1.82,83.0,8.400,90.0,932.0
inFAMOUS: Second Son,2014,Sucker Punch,2.79,80.0,7.900,90.0,2944.0
nail'd,2010,Techland,0.23,65.0,6.650,85.0,29.0
pro evolution soccer 2011,2010,Konami,4.03,77.0,5.975,102.0,130.0
uDraw Studio: Instant Artist,2011,THQ,0.02,54.0,5.700,5.0,6.0

In [52]:
platform_agg_df.columns

Index(['year_of_release', 'worldwide_sales', 'critic_score', 'critic_count',
       'user_count'],
      dtype='object')

In [56]:
platform_agg_df.loc["Wii Sports"]

year_of_release    2006.00
worldwide_sales      82.54
critic_score         76.00
critic_count         51.00
user_count          322.00
Name: Wii Sports, dtype: float64

In [ ]:
#Creating new df for each table to simplify importation. 
details_df = merged_video_games_df[['name', 'platform', 'year_of_release', 'genre', 'publisher', 'developer', 'rating']].copy()
details_df.head(10)

In [ ]:
reviews_df = merged_video_games_df[['name', 'critic_score', 'critic_count', 'user_score', 'user_count']].copy()
reviews_df.head(10)

In [ ]:
sales_df = merged_video_games_df[['name', 'na_sales', 'eu_sales', 'jp_sales', 'other_sales', 'global_sales']].copy()
sales_df.head(10)

In [ ]:
# check for duplicates
duplicates = details_df.duplicated()

# print the rows that are duplicates
print(details_df[duplicates])

#How to handle duplicates?
details_df.to_csv('details.csv')

In [ ]:
# check for duplicates
duplicates = reviews_df.duplicated()

# print the rows that are duplicates
print(reviews_df[duplicates])

#How to handle duplicates?
reviews_df.to_csv('reviews.csv')

In [ ]:
# check for duplicates
duplicates = sales_df.duplicated()

# print the rows that are duplicates
print(sales_df[duplicates])

#How to handle duplicates?
sales_df.to_csv('sales.csv')

In [70]:
platform_agg_df.to_csv('platform_agg.csv')